services:
  postgres:
    image: postgres:14
    container_name: stock_market_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-stockuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-stockpassword}
      POSTGRES_DB: ${DB_NAME:-stock_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: