
networks:
  stock_network:
services:
  postgres:
    image: postgres:14
    container_name: stock_market_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-stockuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-stockpassword}
      POSTGRES_DB: ${DB_NAME:-stock_db}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - stock_network
  
  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    ports:
      - 8080:80
    depends_on:
      - postgres
    networks:
      - stock_network